set-option -g status "on"
set-option -g status-position bottom
set-option -g status-justify "left"
set-option -g status-style NONE
set-option -g status-left-style NONE
set-option -g status-right-style NONE
set-option -g status-left-length "100"
set-option -g status-right-length "100"
set-option -g status-left ""
set-option -g status-right "#[fg=black,bg=yellow] %Y-%m-%d #[bg=black] #[fg=black,bg=yellow] %I:%M #[bg=black] #[fg=black,bg=yellow] %p #[bg=black] #[fg=black,bg=blue] #(whoami) "
set-option -g window-status-format "#[fg=black,bg=yellow] #W "
set-option -g window-status-current-format "#[fg=black,bg=blue] #W "
set-option -g pane-border-style "fg=black"
set-option -g pane-active-border-style "fg=blue"
